[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-3",
    "lockscreen-login-box@DP-6",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000008",
    "lockscreen-widget-0000000000000009",
    "lockscreen-widget-000000000000000a",
    "lockscreen-widget-000000000000000b",
    "lockscreen-widget-000000000000000c",
    "lockscreen-widget-000000000000000d"
]

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 720.0
    cx = 1720.0
    cy = 1321.0
    output = "DP-3"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-6"]
    box_height = 196.0
    box_width = 720.0
    cx = 1720.0
    cy = 1385.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-6".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 128.0
    box_width = 296.0
    cx = 1720.0
    cy = 792.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10.0
        background_radius = 12.0
        color = "on_surface"
        font_family = ""
        hide_when_no_media = false
        layout = "horizontal"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 128.0
    box_width = 200.0
    cx = 1908.0
    cy = 656.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10.0
        background_radius = 12.0
        color = "primary"
        color2 = "secondary"
        font_family = ""
        shadow = true
        show_label = true
        stat = "cpu_usage"
        stat2 = ""

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 128.0
    box_width = 200.0
    cx = 1700.0
    cy = 656.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        stat = "net_rx"
        stat2 = "net_tx"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 128.0
    box_width = 128.0
    cx = 1944.0
    cy = 792.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        clock_style = "analog"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 128.0
    box_width = 160.0
    cx = 1512.0
    cy = 656.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        forecast_days = 3
        show_forecast = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 128.0
    box_width = 128.0
    cx = 1496.0
    cy = 792.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "sticker"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        image_path = "/home/skultix/pfp.jpg"
        opacity = 1.0

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 0.0
    box_width = 0.0
    cx = 28.0
    cy = 1412.0
    output = "DP-6"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        background = false
        command = "systemctl suspend"
        glyph = "moon-stars"
        variant = "default"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000008]
    box_height = 0.0
    box_width = 0.0
    cx = 28.0
    cy = 1412.0
    output = "DP-3"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000008.settings]
        background = false
        command = "systemctl suspend"
        glyph = "nightlight-forced"
        variant = "default"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000009]
    box_height = 128.0
    box_width = 128.0
    cx = 1552.0
    cy = 648.0
    output = "DP-3"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = -0.0
    type = "sticker"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000009.settings]
        image_path = "/home/skultix/pfp.jpg"
        opacity = 1.0

    [lockscreen_widgets.widget.lockscreen-widget-000000000000000a]
    box_height = 128.0
    box_width = 288.0
    cx = 1776.0
    cy = 648.0
    output = "DP-3"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "media_player"

    [lockscreen_widgets.widget.lockscreen-widget-000000000000000b]
    box_height = 128.0
    box_width = 128.0
    cx = 1496.0
    cy = 792.0
    output = "DP-3"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000000b.settings]
        clock_style = "analog"

    [lockscreen_widgets.widget.lockscreen-widget-000000000000000c]
    box_height = 128.0
    box_width = 192.0
    cx = 1672.0
    cy = 792.0
    output = "DP-3"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000000c.settings]
        display = "graph"
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [lockscreen_widgets.widget.lockscreen-widget-000000000000000d]
    box_height = 128.0
    box_width = 192.0
    cx = 1880.0
    cy = 792.0
    output = "DP-3"
    placement_height = 1440.0
    placement_width = 3440.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-000000000000000d.settings]
        color = "tertiary"
        stat = "gpu_usage"
        stat2 = "gpu_temp"
