[accessibility]
ui_scale = 1.0

[bar]
order = [ "main" ]

    [bar.main]
    auto_hide = true
    background_opacity = 0.69999998435378075
    center = [ "control-center", "active_window" ]
    enabled = true
    end = [ "media", "tray", "brightness", "battery", "clock", "caffeine", "notifications" ]
    margin_edge = 8
    margin_ends = 8
    padding = 12
    position = "top"
    radius = 12
    reserve_space = false
    scale = 1.0
    start = [ "session", "cpu", "sysmon", "ram", "network", "bluetooth", "volume" ]
    thickness = 34
    widget_spacing = 12

[calendar]
enabled = true

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[desktop_widgets]
enabled = false

[dock]
auto_hide = true
enabled = true
pinned = [ "vivaldi-stable", "discord", "signal", "com.github.th_ch.youtube_music" ]
reserve_space = false

[keybinds]
cancel = [ "escape" ]
down = [ "down" ]
left = [ "left" ]
right = [ "right" ]
up = [ "up" ]
validate = [ "return" ]

[location]
address = "Brisbane, Australia"
auto_locate = false

[nightlight]
enabled = false
temperature_day = 6500
temperature_night = 4000

[notification]
enable_daemon = true

[osd]
position = "top_right"

	[osd.kinds]
	media = false

[shell]
avatar_path = "/home/skultix/cloud/google-drive/pfp/grimm.jpg"
password_style = "random"
screen_time_enabled = true
telemetry_enabled = false

    [[shell.session.actions]]
    action = "lock"
    enabled = true

    [[shell.session.actions]]
    action = "suspend"
    enabled = true

    [[shell.session.actions]]
    action = "logout"
    enabled = true

    [[shell.session.actions]]
    action = "reboot"
    enabled = true

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/skultix/wallpapers"
enabled = true
fill_mode = "crop"
transition_duration = 1000
transition_on_startup = true

    [wallpaper.default]
    path = "/home/skultix/wallpapers/firewatch.jpeg"

    [wallpaper.last]
    path = "/home/skultix/wallpapers/firewatch.jpeg"

    [[wallpaper.favorite]]
    builtin_palette = "Catppuccin"
    palette_source = "builtin"
    path = "/home/skultix/wallpapers/firewatch.jpeg"
    theme_mode = "dark"

[weather]
effects = true
enabled = true
unit = "celsius"

[widget.active_window]
title_scroll = "on_hover"

[widget.bluetooth]
hide_when_no_connected_device = true
show_label = true

[widget.control-center]
glyph = "layout-2-filled"

[widget.media]
hide_when_no_media = true

[widget.spacer_2]
type = "spacer"

[widget.sysmon]
stat = "gpu_usage"

[widget.workspaces]
show_labels = false
