#!/bin/sh

pattern="^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\([a-zA-Z0-9_-]+\))?!?: .+"

commit_msg=$(cat "$1")

if ! echo "$commit_msg" | grep -qE "$pattern"; then
	echo "❌ Commit message does not follow Conventional Commits format."
	exit 0
fi
